### ISSUE TITLE
Archer C7 ?

### ISSUE THREAD

**Issue by big-muscle** [menahishayan/Home-Assistant-TP-Link-Router#2]
Hello,

I try to use the Home-Assistant-TP-Link-Router package in HA, to switch on / off the 5 ghz band of my Archer C7 router (the night).
I didn't find it on HACS so i c/c on my custom_components folder. I added the configuration in my yml.
But after restarting, i get this error :

```
2021-02-01 20:42:01 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.tplink_router_24ghz fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/tplink_router/switch.py", line 105, in async_update
    self._state = result['[1,1,0,0,0,0]0']['enable'] == '1'
KeyError: '[1,1,0,0,0,0]0'
```

Does it means it is not compatible with the Archer C7 ? Or just i did'nt added it correctly ?

Thanks for your answer ;)

**Comment by AlexandrErohin** [comment]
If you are still looking for Home Assistant Integration for Archer C7 v5.0 - I have one https://github.com/AlexandrErohin/home-assistant-tplink-router
